// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByIKlwZDdNoUaCk9lDFl_X-VoEX9lB9fk',
    appId: '1:996189296114:web:0e34e3c2456c3f9aeb476b',
    messagingSenderId: '996189296114',
    projectId: 'rojgari-app-c4488',
    authDomain: 'rojgari-app-c4488.firebaseapp.com',
    storageBucket: 'rojgari-app-c4488.firebasestorage.app',
    measurementId: 'G-M47ZEMET81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDAKDQlCx5_GUQrgmgjKSJM3pUVrSCek',
    appId: '1:996189296114:android:26bc9ad69fec8ea4eb476b',
    messagingSenderId: '996189296114',
    projectId: 'rojgari-app-c4488',
    storageBucket: 'rojgari-app-c4488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlimkqvByv_kUu5X4UjrzMxVc2iioDl-o',
    appId: '1:996189296114:ios:5b986bb66bef8799eb476b',
    messagingSenderId: '996189296114',
    projectId: 'rojgari-app-c4488',
    storageBucket: 'rojgari-app-c4488.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
